title: "Aarhus GAA"
description: "We are a Gaelic Football team in the heart of Denmark. Come join us for some fun, sport and socialising!"
baseurl: ""
url: "https://lukejconnelly.github.io"
logo: "/assets/logo.jpg"
show_downloads: false

remote_theme: "pages-themes/minimal@v0.2.0"
plugins:
  - jekyll-remote-theme

github:
  is_user_page: false
