title: Coming Soon
description: Wait and see...
baseurl: ""
url: "https://lukejconnelly.github.io"
logo: "_assets/image.png"
showdownloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
